=== jeremyosborne/dnpk/src/data/effect/schema.json
{
  "$id": "https://jeremyosborne.com/dnpk/effect.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "effect",
  "type": "object",
  "description": "Defines a single, particular, longer term effect.",
  "properties": {
    "documentation": {
      "description": "Human friendly documentation that can be stored with the (human unfriendly) JSON. For optimized systems, this attribute should be pruned at run time.",
      "type": "string"
    },
    "duration": {
      "description": "Number of turns this effect will last. Default duration of -1 describes a permanent effect.",
      "default": -1,
      "type": "integer"
    },
    "id": {
      "description": "Unique id for a particular instance of this type. Effects provided in nested data structures should not need an id.",
      "type": "string"
    },
    "magnitude": {
      "description": "Power level of this particular effect. Not always applicable for an effect.",
      "type": "integer"
    },
    "name": {
      "description": "Descriptive, unique name for this effect.",
      "type": "string"
    }
  }
}

=== jeremyosborne/dnpk/data-sources/moddables/effect/constitution.json
{
  "name": "constitution",
  "documentation": "Provides an individual unit health modification. Duration and magnitude are considered defaults, these values will often be edited. Meta-data provides the reasoning for why this bonus was applied, where it comes from.",
  "duration": -1,
  "magnitude": 1
}

=== jeremyosborne/dnpk/data-sources/moddables/effect/constitution-aura.json
{
  "name": "constitution-aura",
  "documentation": "Provides a group wide health modification. Duration and magnitude are considered defaults, these values will often be edited. Meta-data provides the reasoning for why this bonus was applied, where it comes from.",
  "duration": -1,
  "magnitude": 1
}
