=== jeremyosborne/dnpk/data-sources/moddables/schema/rules.schema.json
{
  "$id": "https://jeremyosborne.com/dnpk/rules.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "rules",
  "description": "Optionally configurable rules for game mechanics, unit availability, economics, etc.",
  "type": "object",
  "properties": {
    "armyGroupSizeMax": {
      "description": "The normal, maximum size of a single army-group on a single map tile.",
      "default": 8,
      "minimum": 1,
      "type": "integer"
    },
    "armyHealthMax": {
      "description": "After all health modifications are considered, cap the maximum effective health of an army at this value.",
      "default": 10,
      "minimum": 1,
      "type": "integer"
    },
    "armyHealthMin": {
      "description": "After all health modifications are considered, prevent the minimum effective health of an army from falling below this value.",
      "default": 1,
      "minimum": 1,
      "type": "integer"
    },
    "armyHealthModifierMax": {
      "description": "After all health modifications are considered, cap the maximum effective health of an army at this value.",
      "default": 10,
      "minimum": 1,
      "type": "integer"
    },
    "armyHealthModifierMin": {
      "description": "After all health modifications are considered, prevent the minimum effective health of an army from falling below this value.",
      "default": -10,
      "maximum": 0,
      "type": "integer"
    },
    "armyStrengthMax": {
      "description": "After all bonuses are considered, cap the effective strength of an army at this value. It should be at least one less than the maximum value rolled by a battle dice.",
      "default": 9,
      "minimum": 1,
      "type": "integer"
    },
    "armyStrengthMin": {
      "description": "After all strength modifications are considered, provide a floor for the effective strength below which an army unit won't fall.",
      "default": 0,
      "minimum": 0,
      "type": "integer"
    },
    "armyStrengthModifierMax": {
      "description": "The maximum positive bonus of external modifications that can be applied to an army's strength.",
      "default": 10000,
      "minimum": 0,
      "type": "integer"
    },
    "armyStrengthModifierMin": {
      "description": "The minimum negative malus of external modifications that can be applied to an army's strength.",
      "default": -10000,
      "maximum": 0,
      "type": "integer"
    },
    "battleDiceNumFaces": {
      "description": "The number of sides available on the standard battle dice.",
      "default": 10,
      "minimum": 2,
      "type": "integer"
    },
    "createdAt": {
      "description": "Human time when this object was created, ISO format.",
      "format": "date-time",
      "type": "string"
    },
    "documentation": {
      "description": "Human friendly documentation that can be stored with the (human unfriendly) JSON. For optimized systems, this attribute should be pruned at run time.",
      "type": "string"
    },
    "heroesMax": {
      "description": "Maximum number of heroes each empire is allowed to have at any one time.",
      "default": 5,
      "minimum": 0,
      "type": "integer"
    },
    "name": {
      "description": "Rule sets need a distinct name and should say something about the rules defined within.",
      "type": "string"
    },
    "type": {
      "enum": ["rules"],
      "default": "rules",
      "description": "duck typing",
      "type": "string"
    }
  }
}

=== jeremyosborne/dnpk/data-sources/moddables/rules/sequel.json
{
  "documentation": "Rules to make the game similar to Warlords II.",
  "armyGroupSizeMax": 8,
  "armyHealthMax": 10,
  "armyHealthMin": 1,
  "armyHealthModifierMax": 4,
  "armyHealthModifierMin": -2,
  "armyStrengthMax": 15,
  "armyStrengthMin": 0,
  "armyStrengthModifierMax": 5,
  "armyStrengthModifierMin": -5,
  "battleDiceNumFaces": 20,
  "heroesMax": 5,
  "name": "sequel"
}

=== jeremyosborne/dnpk/data-sources/moddables/rules/classic.json
{
  "documentation": "Rules and configuration options to make the game as similar to the original Warlords as possible.",
  "armyGroupSizeMax": 8,
  "battleDiceNumFaces": 10,
  "heroesMax": 5,
  "name": "classic",
  "armyStrengthMax": 9,
  "armyStrengthMin": 0,
  "armyStrengthModifierMax": 10000,
  "armyStrengthModifierMin": -10000
}

=== jeremyosborne/dnpk/data-sources/moddables/rules/tweaked.json
{
  "documentation": "Customized rules that try things further away from the original warlords.",
  "armyGroupSizeMax": 20,
  "armyHealthMax": 20,
  "armyHealthMin": 1,
  "armyHealthModifierMax": 6,
  "armyHealthModifierMin": -4,
  "armyStrengthMax": 16,
  "armyStrengthMin": 1,
  "armyStrengthModifierMax": 5,
  "armyStrengthModifierMin": -5,
  "battleDiceNumFaces": 20,
  "heroesMax": 10,
  "name": "tweaked"
}
