=== jeremyosborne/dnpk/src/config-game-objects/schema/defs/army.schema.json
{
  "$id": "https://jeremyosborne.com/dnpk/army.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "army",
  "type": "object",
  "description": "Defines a distinct army type, from which single entity instances are generated in game.",
  "properties": {
    "documentation": {
      "description": "Human friendly documentation that can be stored with the (human unfriendly) JSON. For optimized systems, this attribute should be pruned at run time.",
      "type": "string"
    },
    "equipment": {
      "default": [],
      "description": "Inventory carried by the unit.",
      "items": {
        "$ref": "https://jeremyosborne.com/dnpk/equippable.schema.json"
      },
      "type": "array"
    },
    "health": {
      "default": 2,
      "description": "The base number of successful attacks any instance of this unit type can suffer before dying.",
      "type": "integer"
    },
    "id": {
      "description": "Unique id for a particular instance of this type.",
      "type": "string"
    },
    "effects": {
      "default": [],
      "description": "Longer term effects inflicted on this specific unit instance beyond birth.",
      "items": {
        "$ref": "https://jeremyosborne.com/dnpk/effect.schema.json"
      },
      "type": "array"
    },
    "movementSpeed": {
      "description": "The number of squares per turn this unit can move over ideal terrain.",
      "type": "integer"
    },
    "name": {
      "description": "Descriptive, display name for this type of army.",
      "examples": [
        "Heavy Infantry",
        "Light Infantry"
      ],
      "type": "string"
    },
    "nameInstance": {
      "description": "Unique name for the unit",
      "examples": [
        "Vorgoth the Timid, Destroyer of Lint Bunnies"
      ],
      "type": "string"
    },
    "strength": {
      "description": "Base, unmodified attack/defense strength of the unit.",
      "type": "integer"
    },
    "type": {
      "enum": ["army"],
      "default": "army",
      "description": "duck typing",
      "type": "string"
    }
  }
}

=== jeremyosborne/dnpk/data-sources/moddables/army/mountaineer.json
{
  "health": 2,
  "effects": [
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "brawn-terrain-modifier",
      "magnitude": 1,
      "metadata": {
        "name": "hill"
      }
    }
  ],
  "movementSpeed": 9,
  "name": "mountaineer",
  "strength": 5
}

=== jeremyosborne/dnpk/data-sources/moddables/army/wolf-rider.json
{
  "health": 2,
  "effects": [
    {
      "name": "terrain-modifier-brawn",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "terrain-modifier-brawn",
      "magnitude": -1,
      "metadata": {
        "name": "hill"
      }
    }
  ],
  "movementSpeed": 14,
  "name": "wolf-rider",
  "strength": 5
}

=== jeremyosborne/dnpk/data-sources/moddables/army/elven-archer.json
{
  "health": 2,
  "effects": [
    {
      "name": "terrain-battle-modifier",
      "magnitude": 1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "terrain-battle-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "hill"
      }
    },
    {
      "name": "terrain-battle-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "marsh"
      }
    }
  ],
  "movementSpeed": 12,
  "name": "elven-archer",
  "strength": 4
}

=== jeremyosborne/dnpk/data-sources/moddables/army/dwarf.json
{
  "health": 2,
  "effects": [
    {
      "name": "terrain-modifier-brawn",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "terrain-modifier-brawn",
      "magnitude": 1,
      "metadata": {
        "name": "hill"
      }
    }
  ],
  "movementSpeed": 9,
  "name": "dwarf",
  "strength": 5
}

=== jeremyosborne/dnpk/src/config-game-objects/army/defs/dwarf.json
{
  "health": 2,
  "effects": [
    {
      "name": "terrain-battle-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "terrain-battle-modifier",
      "magnitude": 1,
      "metadata": {
        "name": "hill"
      }
    }
  ],
  "movementSpeed": 9,
  "name": "dwarf",
  "strength": 5
}

=== jeremyosborne/dnpk/data-sources/moddables/army/cavalry.json
{
  "health": 2,
  "effects": [
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "hill"
      }
    },
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "marsh"
      }
    }
  ],
  "movementSpeed": 18,
  "name": "cavalry",
  "strength": 6
}

=== jeremyosborne/dnpk/data-sources/moddables/army/ranger.json
{
  "health": 2,
  "effects": [
    {
      "name": "brawn-terrain-modifier",
      "magnitude": 1,
      "metadata": {
        "appliesTo": "forest"
      }
    },
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "appliesTo": "hill"
      }
    },
    {
      "name": "brawn-terrain-modifier",
      "magnitude": -1,
      "metadata": {
        "appliesTo": "marsh"
      }
    }
  ],
  "movementSpeed": 12,
  "name": "ranger",
  "strength": 4
}

=== jeremyosborne/dnpk/data-sources/game-objects/army/wolf-rider.json
{
  "health": 2,
  "effects": [
    {
      "name": "terrain-battle-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "forest"
      }
    },
    {
      "name": "terrain-battle-modifier",
      "magnitude": -1,
      "metadata": {
        "name": "hill"
      }
    }
  ],
  "movementSpeed": 14,
  "name": "wolf-rider",
  "strength": 5
}
